name: nimphelos
description: Nimphelos simplifies error handling and network operations in Flutter. It manages service calls and handles exceptions, including Dio and JSON errors.
version: 1.0.0
homepage: https://github.com/fatiharge/nimphelos.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

example:
  name: example
  description: An example Flutter app showcasing how to use the Nimphelos package.

flutter: